server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
spring:
  application:
    name: ApiGateway
  cloud.gateway:
    discovery:
      locator:
        enabled: true
        lowerCaseServiceId: true
    routes:
      - id: location-service
        uri: http://localhost:8081/
        predicates:
          - Path=/location/**
      - id: item-service
        uri: http://localhost:8082/
        predicates:
          - Path=/items/**